# Generated by Django 4.1.3 on 2023-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_city_remove_account_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='access_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
