# Generated by Django 4.1.3 on 2022-12-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspaceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
