# Generated by Django 4.1.2 on 2022-12-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspaceapp', '0002_studyspace_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='group_space',
            field=models.BooleanField(default=False),
        ),
    ]
