# Generated by Django 4.1.3 on 2022-12-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspaceapp', '0003_studyspace_group_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='pc_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='powered_seating',
            field=models.BooleanField(default=False),
        ),
    ]
