# Generated by Django 4.1.3 on 2022-12-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspaceapp', '0004_studyspace_pc_available_studyspace_powered_seating'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
